# -*- coding: utf-8 -*-
"""Phishing EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1akH9-aL2ltgMRXv5usey_AFoMEIvYSrz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("phishing_url_dataset 3.csv")

df.head()

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print(df.columns.tolist())

df.info()

df.describe()

df.isnull().sum()

print("Number of duplicate rows:", df.duplicated().sum())

print(df["target"].value_counts())

plt.figure(figsize=(6,4))

sns.countplot(data=df, x="target")

plt.title("Target Class Distribution")
plt.xlabel("Target")
plt.ylabel("Count")

plt.show()

df.hist(figsize=(16,12), bins=20)

plt.tight_layout()
plt.show()

numeric_features = df.select_dtypes(include=np.number).columns.tolist()

numeric_features.remove("target")

for col in numeric_features:
    plt.figure(figsize=(7,3))
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot of {col}")
    plt.xlabel(col)
    plt.show()

correlation = df.corr(numeric_only=True)

plt.figure(figsize=(12,9))

sns.heatmap(
    correlation,
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")

plt.show()

target_corr = correlation["target"].drop("target").sort_values(
    key=abs,
    ascending=False
)

print(target_corr)

for col in numeric_features:
    plt.figure(figsize=(7,4))

    sns.boxplot(
        data=df,
        x="target",
        y=col
    )

    plt.title(f"{col} vs Target")
    plt.xlabel("Target")
    plt.ylabel(col)

    plt.show()

print("EDA SUMMARY")
print("=" * 40)

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Number of target classes:", df["target"].nunique())