# -*- coding: utf-8 -*-
"""Phishing _URL _Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FhjKzwGPFxv_lZH7fJz21uEEpJnidwBs
"""

!python phishing_eda.py

!python phishing_model_final_colab\ \(2\).py

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/phishing_url_dataset 3.csv")

plt.figure(figsize=(6,4))

sns.countplot(x="target", data=df)

plt.title("Class Distribution")
plt.xlabel("Target (0 = Legitimate, 1 = Phishing)")
plt.ylabel("Number of URLs")

plt.show()

plt.figure(figsize=(6,4))

sns.histplot(df["url_length"], bins=30, kde=True)

plt.title("URL Length Distribution")
plt.xlabel("URL Length")
plt.ylabel("Frequency")

plt.show()

df.hist(figsize=(12,10), bins=20)

plt.suptitle("Feature Distributions")

plt.show()

plt.figure(figsize=(12,6))

sns.boxplot(data=df)

plt.title("Boxplot of Numerical Features")
plt.xticks(rotation=90)

plt.show()

plt.figure(figsize=(12,8))

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")

plt.show()

plt.figure(figsize=(6,4))

sns.boxplot(x="target", y="url_length", data=df)

plt.title("URL Length vs Target")
plt.xlabel("Target (0 = Legitimate, 1 = Phishing)")
plt.ylabel("URL Length")

plt.show()

plt.figure(figsize=(6,4))

sns.boxplot(x="target", y="path_length", data=df)

plt.title("Path Length vs Target")
plt.xlabel("Target (0 = Legitimate, 1 = Phishing)")
plt.ylabel("Path Length")

plt.show()

plt.figure(figsize=(6,4))

sns.boxplot(x="target", y="sensitive_words_count", data=df)

plt.title("Sensitive Words Count vs Target")
plt.xlabel("Target (0 = Legitimate, 1 = Phishing)")
plt.ylabel("Sensitive Words Count")

plt.show()

plt.figure(figsize=(6,4))

sns.countplot(x="isHttps", hue="target", data=df)

plt.title("HTTPS Status vs Target")
plt.xlabel("HTTPS Status")
plt.ylabel("Number of URLs")

plt.show()